giant rat
forest wolf
goblin
wild horse
theif
timber wolf
bandit
goblin zerker
forest bear
forest bear summon
demonic goblin
necro practicioner
willothewisp
spriggan
minotaur
treant
bandit vetteran
bandit vet spearman
goblin shaman
spriggan guardian
foerst spider
land scorpion
necro initiate
ogre
bandit lord
ogre magi
failed experiment
minotaur lord
necro acolyte
forest bair (raid)
skeleton
minotaur (raid)
ghost
giant boulock
mountain giant
stone turtle
zombie